ecomm/ecomm/urls.py
from django.contrib import admin
from django.urls import path
from ecommapp import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home.as_view(),name='home_view'),
    path('user/reg',views.RegView.as_view(),name='reg_view'),
    path('user/log',views.LoginView.as_view(),name='log_view'),
    path('user/logout',views.LogoutView.as_view(),name='logout_view'),
    path('product/detail/<int:id>',views.ProductDetailview.as_view(),name='detail_view'),
    path('add/cart/<int:id>',views.AddTocartView.as_view(),name='addtocart_view'),
    path('cart/list',views.CartListView.as_view(),name='cartlist_view'),
    path('place/order/<int:cart_id>',views.placeOrderView.as_view(),name='order_view'),
    path('place/delete/<int:id>',views.CartDeleteView.as_view(),name='cartdelete_view'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomm/ecommapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    category_name=models.CharField(max_length=100)
    is_active=models.BooleanField(default=True)

    def __str__(self):
        return self.category_name
    
class Products(models.Model):
    product_name=models.CharField(max_length=100)
    price=models.PositiveBigIntegerField()
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='image',null=True)
    description=models.CharField(max_length=100)


    def __str__(self):
        return self.product_name
    

class Carts(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    quantity=models.PositiveBigIntegerField(default=1)
    options=(
        ('in-cart','in-cart'),
        ('cancelled','cancelled'),
        ('order-placed','order-placed')
    )
    status=models.CharField(max_length=100,choices=options,default='in-cart')

class Orders(models.Model):
        user=models.ForeignKey(User,on_delete=models.CASCADE)
        cart=models.ForeignKey(Carts,on_delete=models.CASCADE)
        order_date=models.DateTimeField(auto_now_add=True)
        address=models.TextField(max_length=255)
        email=models.EmailField()
        options=(
            ('order-placed','order-placed'),
            ('cancelled','cancelled'),
            ('dispatched','dispatched'),
            ('delivered','delivered')
        )
        status=models.CharField(max_length=100,choices=options,default='order-placed')

ecomm/ecommapp/forms.py
from django import forms
from django.contrib.auth.models import User
from ecommapp.models import Carts,Orders

class UserRegister(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','password','email']

        widgets={
            'first_name':forms.TextInput(attrs={'class':"form-control",'placehoder':'FirstName'}),
            'last_name':forms.TextInput(attrs={'class':"form-control",'placehoder':'LastName'}),
            'username':forms.TextInput(attrs={'class':"form-control",'placehoder':'UserName'}),
            'password':forms.TextInput(attrs={'class':"form-control",'placehoder':'Password'}),
            'email':forms.TextInput(attrs={'class':"form-control",'placehoder':'Email Id'}),
            

        }

class UserLogin(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','password']
        widgets={
            'username':forms.TextInput(attrs={'class':"form-control",'placeholder':'UserName'}),
            'password':forms.PasswordInput(attrs={'class':"form-control",'placeholder':'Password'}),
        }


class CartForm(forms.ModelForm):
    class Meta:
        model=Carts
        fields=['quantity']
        widgets={
                    'quantity':forms.NumberInput(attrs={'class':"form-control"})


        }

class OrderForm(forms.ModelForm):
    class Meta:
        model=Orders
        fields=['address','email']
        widgets={
            'address':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'})
        }

ecomm/ecommapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views import View
from .forms import UserRegister,UserLogin,CartForm,OrderForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from ecommapp.models import Products,Carts,Orders
from django.core.mail import send_mail,settings

# Create your views here.

class Home(View):
    
    def get(self,request,*args,**kwargs):
        data=Products.objects.all()
        return render(request,'index.html',{'products':data})
    
class RegView(View):
    def get(self,request,*args,**kwargs):
       form=UserRegister()
       return render(request,'regform.html',{'form':form})
    
    def post(self,request,*args,**kwargs):
        # first=request.POST.get('first_name')
        # last=request.POST.get('last_name')
        # username=request.POST.get('username')
        # password=request.POST.get('password')
        # email=request.POST.get('email')
        form=UserRegister(request.POST)
        if form.is_valid():
            User.objects.create_user(**form.cleaned_data)
            messages.success(request,'registration successfull')
            return HttpResponse('success')
        else:
            messages.error(request,'invalid')
            return redirect('log_view')
        
class LoginView(View):
    def get(self,request,*args,**kwargs):
        form=UserLogin()
        return render(request,'userlogin.html',{'form':form})
    
    def post(self,request,*args,**kwargs):
        form=UserLogin(request.POST)
    
        uname=request.POST.get('username')
        passw=request.POST.get('password')
        user=authenticate(request,username=uname,password=passw)
        if user:
            login(request,user)
            messages.success(request,'login successfull')
            return redirect('home_view')
        else:
            messages.error(request,'invalid')
            return redirect('log_view')
        
class LogoutView(View):
      def get(self,request,*args,**kwargs):
          logout(request)
          messages.success(request,'logout successfull')
          return redirect('home_view')
      
class ProductDetailview(View):
    def get(self,request,*args,**kwargs):
        id=kwargs.get('id')
        product=Products.objects.get(id=id)
        return render(request,'productdetail.html',{'product':product})
    
class AddTocartView(View):
    def get(self,request,*args,**kwargs):
                form=CartForm()
                id=kwargs.get('id')
                product=Products.objects.get(id=id)
                return render(request,'addtocart.html',{'form':form,'product':product})
    
    def post(self,request,*args,**kwargs):
            id=kwargs.get('id')
            product=Products.objects.get(id=id)
            user=request.user
            quantity=request.POST.get('quantity')
            Carts.objects.create(product=product,user=user,quantity=quantity)
            return redirect('home_view')
    
class CartListView(View):
    def get(self,request,*args,**kwargs):
    
        cart=Carts.objects.filter(user=request.user).exclude(status='order_placed')
        return render(request,'cartlistview.html',{'cart':cart}) 
    
class placeOrderView(View):
     def get(self,request,*args,**kwargs):
          form=OrderForm()
          return render(request,'place-order.html',{'form':form}) 

     def post(self,request,*args,**kwargs):
        cart_id=kwargs.get('cart_id')
        cart=Carts.objects.get(id=cart_id)
        user=request.user
        address=request.POST.get('address')
        email=request.POST.get('email')
        Orders.objects.create(user=user,cart=cart,address=address,email=email)
        send_mail('confirmation','order placed successfully!',settings.EMAIL_HOST_USER,[email])
        cart.status='order_placed'
        cart.save()
        return redirect('home_view')

class CartDeleteView(View):
    def get(self,request,*args,**kwargs):
        id=kwargs.get('id')
        data=Carts.objects.get(id=id)
        data.delete()
        return redirect('cartlist_view')

          
     


     

         



        
       
    

    

    

ecomm/ecommapp/templates/addtocart.html
{% extends 'index.html' %}
{% block content %}


<div  class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
    <div class="col-8">
        <div class="card h-100">
            <!-- Product image-->
            <img class="card-img-top" src="{{ product.image.url }}" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">{{product.product_name}}</h5>
                    <!-- Product price-->
                    {{product.price}}<br>
                    {{product.description}}
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'addtocart_view' product.id %}">Add to Cart</a></div>
            </div>
        </div>
    

    </div>
    <div class="col-4">
        
        <form action="" method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit">
        </form>

    </div>


</div>




{% endblock %}

ecomm/ecommapp/templates/cartlistview.html
{% extends 'index.html' %}
{% block content %}

<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for cart in cart %}
        <div class="col mb-5">
            <div class="card h-100">
                <!-- Product image-->
                <img class="card-img-top" src="{{ cart.product.image.url }}" alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{cart.product.product_name}}</h5>
                        <!-- Product price-->
                        {{cart.product.price}}
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'order_view' cart.id %}">Place order</a></div>
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'cartdelete_view' cart.id %}">Remove</a></div>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>




{% endblock %}

ecomm/ecommapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
       
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'reg_view' %}">Register</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'log_view' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'logout_view' %}">Logout</a></li>

                    </ul>
                    <form class="d-flex">
                        <a class="btn btn-outline-dark" type="submit" href="{% url 'cartlist_view' %}">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill">
                                <!-- {% if request.user.carts_set.all.count > 0 %}
                                {{ request.user.carts_set.all.count }}
                                {% else %}
                                0
                                {% endif %} -->
                                {{count}}
                            </span>
                        </a>
                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Shop in style</h1>
                    <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        {% block content %}
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for product in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.image.url }}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{product.product_name}}</h5>
                                    <!-- Product price-->
                                    {{product.price}}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'detail_view' product.id %}">View options</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        {% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

ecomm/ecommapp/templates/place-order.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4"> </div>
        <div class="col-4">
            <form action="" method="POST">
                {% csrf_token %}
                {{form}}
                <input type="submit">
            </form>
            
        </div>
        <div class="col-4"> </div>

    </div>
</div>


{% endblock %}

ecomm/ecommapp/templates/productdetail.html
{% extends 'index.html' %}

{% block content %}
<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

        <div class="col mb-5">
            <div class="card h-100">
                <!-- Product image-->
                <img class="card-img-top" src="{{ product.image.url }}" alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{product.product_name}}</h5>
                        <!-- Product price-->
                        {{product.price}}<br>
                        {{product.description}}
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'addtocart_view' product.id %}">Add to Cart</a></div>
                </div>
            </div>
        </div>
        
    </div>
</div>

{% endblock %}

ecomm/ecommapp/templates/regform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Register">
    </form>
    
</body>
</html>

ecomm/ecommapp/templates/userlogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
    
</body>
</html>